name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Commit and push changes
        run: |
        git config --global user.name "your username"
        git config --global user.email "your email"
        git config --global
        git add -A
        git commit -m "commit message"
        git stash
        git checkout builds
        git stash pop
        git push