name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - name: Maven Package
        uses: actions/upload-artifact@v2
        with:
          path: staging'
          java-version: '16'
          distribution: 'adopt'
